services:
  redis:
    image: redis:7.2
    container_name: redis_service
    ports:
      - "6379:6379"

  miner:
    build:
      context: .
      dockerfile: ./Dockerfile       
    container_name: miner_service
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    depends_on:
      - redis

  visualizer:
    build:
      context: ./visualizer           
      
      dockerfile: ./Dockerfile        
    container_name: visualizer_service
    ports:
      - "5050:5050"
    depends_on:
      - redis
